services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./web
                  target: /src/web
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
        container_name: ${APP_NAME}_app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - db
        env_file:
            - .env
        networks:
            - laravel

    composer:
        image: composer:latest
        working_dir: /var/www/symfony

    db:
        image: postgres:15-alpine
        container_name: ${APP_NAME}_${DB_HOST}
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
